syntax = "proto3";

package drivecountry.v1;

option go_package = "github.com/XoxxxoL-CW/drive-country-proto/gen/go/drivecountry/v1;drivecountryv1";

service HouseUtilitiesService {
  rpc PayDebt(PayDebtRequest) returns (PayDebtResponse);
  rpc TopUpDeposit(TopUpDepositRequest) returns (TopUpDepositResponse);
}

message PayDebtRequest {
  int64 user_id = 1;
  int64 house_id = 2;
}

message PayDebtResponse {}

message TopUpDepositRequest {
  int64 user_id = 1;
  int64 house_id = 2;
  int64 amount_rub = 3;
}

message TopUpDepositResponse {}
